PALAVRAS = [
    "abacaxi", "borboleta", "cachorro", "dinossauro", "elefante",
    "floresta", "girassol", "horizonte", "ilha", "janela",
    "kastelo", "laranja", "macaco", "nuvem", "oceano",
    "palmeira", "queijo", "relógio", "sabiá", "tartaruga",
    "uva", "violão", "xícara", "zebra", "amendoim",
    "biblioteca", "caderno", "diamante", "escada", "farinha",
    "garfo", "hospital", "iguana", "jaguatirica", "lagarto",
    "marmelada", "nebulosa", "óculos", "pinguim", "quadrado",
    "raquete", "sapato", "telescópio", "urso", "ventilador",
    "abóbora", "biscoito", "cenoura", "damasco", "espelho",
    "flauta", "guitarra", "helicóptero", "inseto", "javali",
    "kiwi", "limão", "manga", "navio", "orquídea",
    "papagaio", "querosene", "rinoceronte", "sereia", "tomate",
    "umbrela", "vampiro", "whisky", "xilogravura", "zumbi",
    "aquário", "banana", "camelo", "dragão", "estrela",
    "futebol", "gramado", "harpa", "inverno", "joelho",
    "karatê", "leão", "montanha", "novela", "ovelha",
    "peixe", "queimada", "raio", "sorriso", "trovão",
    "unicórnio", "viagem", "xadrez", "yacaré", "zoológico",
    "abelha", "besouro", "cobra", "dado", "escorpião",
    "fogueira", "golfinho", "hipopótamo", "irmão", "jabuti",
    "lagoa", "melancia", "narval", "ouriço", "porco",
    "quetzal", "raposa", "sururu", "tigre", "urubú",
    "vespa", "wolverine", "xaxim", "yeti", "zinco",
]
